/* Generated By:JavaCC: Do not edit this line. ParserForGetConstants.java */
package parserGetToDatalog;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserForGetConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int get = 5;
  /** RegularExpression Id. */
  int string = 6;
  /** RegularExpression Id. */
  int nullValue = 7;
  /** RegularExpression Id. */
  int number = 8;
  /** RegularExpression Id. */
  int digit = 9;
  /** RegularExpression Id. */
  int name = 10;
  /** RegularExpression Id. */
  int nameValue = 11;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"get\"",
    "<string>",
    "\"null\"",
    "<number>",
    "<digit>",
    "<name>",
    "<nameValue>",
    "\".\"",
    "\"=\"",
  };

}
