/* Generated By:JavaCC: Do not edit this line. ParserRuleToJavaConstants.java */
package parserRuletoJava;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserRuleToJavaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int nullValue = 5;
  /** RegularExpression Id. */
  int variable = 6;
  /** RegularExpression Id. */
  int string = 7;
  /** RegularExpression Id. */
  int operators = 8;
  /** RegularExpression Id. */
  int number = 9;
  /** RegularExpression Id. */
  int digit = 10;
  /** RegularExpression Id. */
  int not = 11;
  /** RegularExpression Id. */
  int kindValue = 12;
  /** RegularExpression Id. */
  int nameValue = 13;
  /** RegularExpression Id. */
  int latest = 14;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"null\"",
    "<variable>",
    "<string>",
    "<operators>",
    "<number>",
    "<digit>",
    "\"not\"",
    "<kindValue>",
    "<nameValue>",
    "<latest>",
    "\":-\"",
    "\".\"",
    "\",\"",
    "\"*\"",
    "\"(\"",
    "\")\"",
  };

}
