/* Generated By:JavaCC: Do not edit this line. ParserQueryToDatalogToJavaConstants.java */
package parserQueryToDatalogToJava;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserQueryToDatalogToJavaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int get = 5;
  /** RegularExpression Id. */
  int add = 6;
  /** RegularExpression Id. */
  int delete = 7;
  /** RegularExpression Id. */
  int copy = 8;
  /** RegularExpression Id. */
  int move = 9;
  /** RegularExpression Id. */
  int string = 10;
  /** RegularExpression Id. */
  int nullValue = 11;
  /** RegularExpression Id. */
  int number = 12;
  /** RegularExpression Id. */
  int digit = 13;
  /** RegularExpression Id. */
  int name = 14;
  /** RegularExpression Id. */
  int nameValue = 15;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"get\"",
    "\"add\"",
    "\"delete\"",
    "\"copy\"",
    "\"move\"",
    "<string>",
    "\"null\"",
    "<number>",
    "<digit>",
    "<name>",
    "<nameValue>",
    "\".\"",
    "\"=\"",
    "\" to \"",
    "\" where \"",
  };

}
