/* Generated By:JavaCC: Do not edit this line. ParserForPutConstants.java */
package parserPutToDatalog;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserForPutConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int marks = 5;
  /** RegularExpression Id. */
  int put = 6;
  /** RegularExpression Id. */
  int open = 7;
  /** RegularExpression Id. */
  int end = 8;
  /** RegularExpression Id. */
  int punkt = 9;
  /** RegularExpression Id. */
  int nullValue = 10;
  /** RegularExpression Id. */
  int string = 11;
  /** RegularExpression Id. */
  int number = 12;
  /** RegularExpression Id. */
  int digit = 13;
  /** RegularExpression Id. */
  int kindValue = 14;
  /** RegularExpression Id. */
  int nameValue = 15;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\\"\"",
    "\"put\"",
    "\"{\"",
    "\"}\"",
    "\":\"",
    "\"null\"",
    "<string>",
    "<number>",
    "<digit>",
    "<kindValue>",
    "<nameValue>",
    "\"(\"",
    "\")\"",
    "\".\"",
    "\",\"",
  };

}
