/* Generated By:JavaCC: Do not edit this line. ParserQueryToDatalogConstants.java */
package parserQueryToDatalog;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserQueryToDatalogConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int add = 5;
  /** RegularExpression Id. */
  int delete = 6;
  /** RegularExpression Id. */
  int copy = 7;
  /** RegularExpression Id. */
  int move = 8;
  /** RegularExpression Id. */
  int string = 9;
  /** RegularExpression Id. */
  int nullValue = 10;
  /** RegularExpression Id. */
  int number = 11;
  /** RegularExpression Id. */
  int digit = 12;
  /** RegularExpression Id. */
  int name = 13;
  /** RegularExpression Id. */
  int nameValue = 14;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"add\"",
    "\"delete\"",
    "\"copy\"",
    "\"move\"",
    "<string>",
    "\"null\"",
    "<number>",
    "<digit>",
    "<name>",
    "<nameValue>",
    "\".\"",
    "\"=\"",
    "\" to \"",
    "\" where \"",
  };

}
