/* Generated By:JavaCC: Do not edit this line. ParserforDatalogToJavaConstants.java */
package parserEDBFactToJava;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserforDatalogToJavaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int nullValue = 5;
  /** RegularExpression Id. */
  int string = 6;
  /** RegularExpression Id. */
  int number = 7;
  /** RegularExpression Id. */
  int digit = 8;
  /** RegularExpression Id. */
  int kindValue = 9;
  /** RegularExpression Id. */
  int nameValue = 10;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"null\"",
    "<string>",
    "<number>",
    "<digit>",
    "<kindValue>",
    "<nameValue>",
    "\".\"",
    "\"(\"",
    "\",\"",
    "\")\"",
  };

}
